using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace MvcSmallScreen.Models
{
    public class SampleData : DropCreateDatabaseIfModelChanges<PCStoreEntities>
    {
        protected override void Seed(PCStoreEntities context)
        {
            var products = new List<Product>
            {
                new Product { Name = "Ноутбук" },
                new Product { Name = "Смартфон" },
                new Product { Name = "Планшет" },
                new Product { Name = "Эл.книга" }
               
            };

            var laptops = new List<Laptop>
            {
                new Laptop { Name = "Alienware" },
                new Laptop { Name = "Samsung" },
                new Laptop { Name = "Packard Bell" },
                new Laptop { Name = "iRu" },
                new Laptop { Name = "MSI" },
                new Laptop { Name = "Nvidia" },
                new Laptop { Name = "Explay" },
                new Laptop { Name = "Supra" },
                new Laptop { Name = "Huawei" },
                new Laptop { Name = "Digma" },
                new Laptop { Name = "Asus" },
                new Laptop { Name = "HP" },
                new Laptop { Name = "Apple" },
                new Laptop { Name = "Philips" },
                new Laptop { Name = "Lenovo" },
                new Laptop { Name = "Dell" },
                new Laptop { Name = "Alcatel" },
                new Laptop { Name = "Fly" },
                new Laptop { Name = "LG" },
                new Laptop { Name = "HTC" },
                new Laptop { Name = "Gmini" },
                new Laptop { Name = "Wexler" },
                new Laptop { Name = "Onyx" },
                new Laptop { Name = "Barnes & Noble" },
                new Laptop { Name = "Amazon" },
                new Laptop { Name = "Nokia" },
                new Laptop { Name = "Microsoft" },
                new Laptop { Name = "PocketBook" },
                new Laptop { Name = "Sony" }
            };

            new List<Goods>
            {
              /*   new Goods { Title = "IdeaPad Z5070", products = products.Single(g => g.Name == "Ноутбук"), Price = 23999, 
                	Laptop = laptops.Single(a => a.Name == "Lenovo"), GoodArtUrl = "/Content/Images/Z5070.jpg" },                	
               new Goods { Title = "MacBook Pro 15", products = products.Single(g => g.Name == "Ноутбук"), Price = 96490, 
                	Laptop = laptops.Single(a => a.Name == "Apple"), GoodArtUrl = "/Content/Images/pro15.jpg" },                	
               new Goods { Title = "X200MA", products = products.Single(g => g.Name == "Ноутбук"), Price = 14490, 
                	Laptop = laptops.Single(a => a.Name == "Asus"), GoodArtUrl = "/Content/Images/x200ma.jpg" },
                new Goods { Title = "G710", products = products.Single(g => g.Name == "Ноутбук"), Price = 20340, 
                	Laptop = laptops.Single(a => a.Name == "Lenovo"), GoodArtUrl = "/Content/Images/g710.jpg" },               	
               new Goods { Title = "G50-30", products = products.Single(g => g.Name == "Ноутбук"), Price = 14500, 
                	Laptop = laptops.Single(a => a.Name == "Lenovo"), GoodArtUrl = "/Content/Images/g50-30.jpg" },               
               new Goods { Title = "INSPIRON 3542", products = products.Single(g => g.Name == "Ноутбук"), Price = 14990, 
                	Laptop = laptops.Single(a => a.Name == "Dell"), GoodArtUrl = "/Content/Images/3542.jpg" },
                new Goods { Title = "G50-70", products = products.Single(g => g.Name == "Ноутбук"), Price = 14990, 
                	Laptop = laptops.Single(a => a.Name == "Lenovo"), GoodArtUrl = "/Content/Images/g50-70.jpg" },               
               new Goods { Title = "PAVILION 17-f100", products = products.Single(g => g.Name == "Ноутбук"), Price = 22590, 
                	Laptop = laptops.Single(a => a.Name == "HP"), GoodArtUrl = "/Content/Images/17-f100.jpg" },               
               new Goods { Title = "ProBook 430 G2", products = products.Single(g => g.Name == "Ноутбук"), Price = 27190, 
                	Laptop = laptops.Single(a => a.Name == "HP"), GoodArtUrl = "/Content/Images/430g2.jpg" },
                   new Goods { Title = "17", products = products.Single(g => g.Name == "Ноутбук"), Price = 117220, 
                	Laptop = laptops.Single(a => a.Name == "Alienware"), GoodArtUrl = "/Content/Images/17.jpg" },                	
         new Goods { Title = "18", products = products.Single(g => g.Name == "Ноутбук"), Price = 146900, 
                	Laptop = laptops.Single(a => a.Name == "Alienware"), GoodArtUrl = "/Content/Images/18.jpg" },                	
              new Goods { Title = "14", products = products.Single(g => g.Name == "Ноутбук"), Price = 85000, 
                	Laptop = laptops.Single(a => a.Name == "Alienware"), GoodArtUrl = "/Content/Images/14.jpg" },                
               new Goods { Title = "M17x", products = products.Single(g => g.Name == "Ноутбук"), Price = 156800, 
                	Laptop = laptops.Single(a => a.Name == "Alienware"), GoodArtUrl = "/Content/Images/m17x.jpg" },               	
               new Goods { Title = "13", products = products.Single(g => g.Name == "Ноутбук"), Price = 89500, 
                	Laptop = laptops.Single(a => a.Name == "Alienware"), GoodArtUrl = "/Content/Images/13.jpg" },               
               new Goods { Title = "Jet 1103", products = products.Single(g => g.Name == "Ноутбук"), Price = 12030, 
                	Laptop = laptops.Single(a => a.Name == "iRu"), GoodArtUrl = "/Content/Images/1103.jpg" },               
               new Goods { Title = "Jet 1706", products = products.Single(g => g.Name == "Ноутбук"), Price = 27980, 
                	Laptop = laptops.Single(a => a.Name == "iRu"), GoodArtUrl = "/Content/Images/1706.jpg" },               
     */            new Goods { Title = "W1002", products = products.Single(g => g.Name == "Ноутбук"), Price = 8850, 
                	Laptop = laptops.Single(a => a.Name == "iRu"), GoodArtUrl = "/Content/Images/w1002.jpg" },               
               new Goods { Title = "K1002s", products = products.Single(g => g.Name == "Ноутбук"), Price = 7400, 
                	Laptop = laptops.Single(a => a.Name == "iRu"), GoodArtUrl = "/Content/Images/k1002s.jpg" },               
               new Goods { Title = "Patriot 522", products = products.Single(g => g.Name == "Ноутбук"), Price = 20320, 
                	Laptop = laptops.Single(a => a.Name == "iRu"), GoodArtUrl = "/Content/Images/522.jpg" },               
              /* new Goods { Title = "EasyNote LG71BM", products = products.Single(g => g.Name == "Ноутбук"), Price = 18990, 
                	Laptop = laptops.Single(a => a.Name == "Packard Bell"), GoodArtUrl = "/Content/Images/lg71bm.jpg" },                	
               new Goods { Title = "EasyNote TG71BM", products = products.Single(g => g.Name == "Ноутбук"), Price = 15490, 
                	Laptop = laptops.Single(a => a.Name == "Packard Bell"), GoodArtUrl = "/Content/Images/tg71bm.jpg" },                	
               new Goods { Title = "EasyNote TF71BM", products = products.Single(g => g.Name == "Ноутбук"), Price = 13990, 
                	Laptop = laptops.Single(a => a.Name == "Packard Bell"), GoodArtUrl = "/Content/Images/tf71bm.jpg" },                
               new Goods { Title = "EasyNote TE69CX", products = products.Single(g => g.Name == "Ноутбук"), Price = 14990, 
                	Laptop = laptops.Single(a => a.Name == "Packard Bell"), GoodArtUrl = "/Content/Images/te69cx.jpg" },               	
               new Goods { Title = "EasyNote TE69HW", products = products.Single(g => g.Name == "Ноутбук"), Price = 25490, 
                	Laptop = laptops.Single(a => a.Name == "Packard Bell"), GoodArtUrl = "/Content/Images/te69hw.jpg" },               
               new Goods { Title = "GE70 2PL Apache", products = products.Single(g => g.Name == "Ноутбук"), Price = 43990, 
                	Laptop = laptops.Single(a => a.Name == "MSI"), GoodArtUrl = "/Content/Images/ge70.jpg" },               
               new Goods { Title = "GP60 2PE Leopard", products = products.Single(g => g.Name == "Ноутбук"), Price = 35500, 
                	Laptop = laptops.Single(a => a.Name == "MSI"), GoodArtUrl = "/Content/Images/gp60.jpg" },               
               new Goods { Title = "GP70 2PE Leopard", products = products.Single(g => g.Name == "Ноутбук"), Price = 47990, 
                	Laptop = laptops.Single(a => a.Name == "MSI"), GoodArtUrl = "/Content/Images/gp70.jpg" },               
               new Goods { Title = "GE70 2PE Apache Pro", products = products.Single(g => g.Name == "Ноутбук"), Price = 56900, 
                	Laptop = laptops.Single(a => a.Name == "MSI"), GoodArtUrl = "/Content/Images/ge70pro.jpg" },               
               new Goods { Title = "GT72 2QE Dominator Pro", products = products.Single(g => g.Name == "Ноутбук"), Price = 124950, 
                	Laptop = laptops.Single(a => a.Name == "MSI"), GoodArtUrl = "/Content/Images/gt72.jpg" },
 
                */
               new Goods { Title = "iPad Air 2 64Gb", products = products.Single(g => g.Name == "Планшет"), Price = 37190, 
                    Laptop = laptops.Single(a => a.Name == "Apple"), GoodArtUrl = "/Content/Images/Air2.jpg" },               
               new Goods { Title = "Galaxy Tab S", products = products.Single(g => g.Name == "Планшет"), Price = 27400, 
                    Laptop = laptops.Single(a => a.Name == "Samsung"), GoodArtUrl = "/Content/Images/tabs.jpg" },               
               new Goods { Title = "IdeaTab A5500", products = products.Single(g => g.Name == "Планшет"), Price = 7890, 
                    Laptop = laptops.Single(a => a.Name == "Lenovo"), GoodArtUrl = "/Content/Images/a5500.jpg" },               
               new Goods { Title = "Xperia Z3 Tablet Compact", products = products.Single(g => g.Name == "Планшет"), Price = 22255, 
                    Laptop = laptops.Single(a => a.Name == "Sony"), GoodArtUrl = "/Content/Images/z3t.jpg" },               
               new Goods { Title = "iPad mini 3", products = products.Single(g => g.Name == "Планшет"), Price = 23970, 
                    Laptop = laptops.Single(a => a.Name == "Apple"), GoodArtUrl = "/Content/Images/i3mini.jpg" },               
               new Goods { Title = "Galaxy Tab 4", products = products.Single(g => g.Name == "Планшет"), Price = 14800, 
                    Laptop = laptops.Single(a => a.Name == "Samsung"), GoodArtUrl = "/Content/Images/tab4.jpg" },    
               new Goods { Title = "IdeaTab A7600", products = products.Single(g => g.Name == "Планшет"), Price = 10450, 
                    Laptop = laptops.Single(a => a.Name == "Lenovo"), GoodArtUrl = "/Content/Images/a7600.jpg" },                
               new Goods { Title = "Yoga Tablet 8", products = products.Single(g => g.Name == "Планшет"), Price = 15745, 
                    Laptop = laptops.Single(a => a.Name == "Lenovo"), GoodArtUrl = "/Content/Images/yogat8.jpg" },               
               new Goods { Title = "Fonepad 7", products = products.Single(g => g.Name == "Планшет"), Price = 4865, 
                    Laptop = laptops.Single(a => a.Name == "Asus"), GoodArtUrl = "/Content/Images/fonepad7.jpg" },
               new Goods { Title = "MeMO Pad 7", products = products.Single(g => g.Name == "Планшет"), Price = 12600, 
                    Laptop = laptops.Single(a => a.Name == "Asus"), GoodArtUrl = "/Content/Images/memo7.jpg" },                  
               new Goods { Title = "Tornado", products = products.Single(g => g.Name == "Планшет"), Price = 4390, 
                    Laptop = laptops.Single(a => a.Name == "Explay"), GoodArtUrl = "/Content/Images/tornado.jpg" },               
               new Goods { Title = "Leader", products = products.Single(g => g.Name == "Планшет"), Price = 4550, 
                    Laptop = laptops.Single(a => a.Name == "Explay"), GoodArtUrl = "/Content/Images/leader.jpg" },               
               new Goods { Title = "Trend 3G", products = products.Single(g => g.Name == "Планшет"), Price = 4290, 
                    Laptop = laptops.Single(a => a.Name == "Explay"), GoodArtUrl = "/Content/Images/trend.jpg" },               
               new Goods { Title = "Cosmic", products = products.Single(g => g.Name == "Планшет"), Price = 7090, 
                    Laptop = laptops.Single(a => a.Name == "Explay"), GoodArtUrl = "/Content/Images/cosmic.jpg" },               
               new Goods { Title = "Style", products = products.Single(g => g.Name == "Планшет"), Price = 8590, 
                    Laptop = laptops.Single(a => a.Name == "Explay"), GoodArtUrl = "/Content/Images/style.jpg" },                              
               new Goods { Title = "MediaPad X1", products = products.Single(g => g.Name == "Планшет"), Price = 19850, 
                    Laptop = laptops.Single(a => a.Name == "Huawei"), GoodArtUrl = "/Content/Images/x1.jpg" },               
               new Goods { Title = "MediaPad M1", products = products.Single(g => g.Name == "Планшет"), Price = 11990, 
                    Laptop = laptops.Single(a => a.Name == "Huawei"), GoodArtUrl = "/Content/Images/m1.jpg" },                
               new Goods { Title = "MediaPad T1", products = products.Single(g => g.Name == "Планшет"), Price = 11781, 
                    Laptop = laptops.Single(a => a.Name == "Huawei"), GoodArtUrl = "/Content/Images/t1.jpg" },               
               new Goods { Title = "MediaPad 10", products = products.Single(g => g.Name == "Планшет"), Price = 14990, 
                    Laptop = laptops.Single(a => a.Name == "Huawei"), GoodArtUrl = "/Content/Images/10.jpg" },                
               new Goods { Title = "MediaPad 7", products = products.Single(g => g.Name == "Планшет"), Price = 6990, 
                    Laptop = laptops.Single(a => a.Name == "Huawei"), GoodArtUrl = "/Content/Images/7.jpg" },                  
               new Goods { Title = "SHIELD Tablet 32Gb LTE", products = products.Single(g => g.Name == "Планшет"), Price = 19750, 
                    Laptop = laptops.Single(a => a.Name == "Nvidia"), GoodArtUrl = "/Content/Images/st32.jpg" },               
               new Goods { Title = "SHIELD Portable 16Gb", products = products.Single(g => g.Name == "Планшет"), Price = 12590, 
                    Laptop = laptops.Single(a => a.Name == "Nvidia"), GoodArtUrl = "/Content/Images/sp16.jpg" },               
               new Goods { Title = "SHIELD Tablet 16Gb Wi-Fi", products = products.Single(g => g.Name == "Планшет"), Price = 17790, 
                    Laptop = laptops.Single(a => a.Name == "Nvidia"), GoodArtUrl = "/Content/Images/st16.jpg" },        
               new Goods { Title = "Platina 7.86 3G", products = products.Single(g => g.Name == "Планшет"), Price = 8650, 
                    Laptop = laptops.Single(a => a.Name == "Digma"), GoodArtUrl = "/Content/Images/7.86.jpg" },               
               new Goods { Title = "Eve 10.3 3G", products = products.Single(g => g.Name == "Планшет"), Price = 12590, 
                    Laptop = laptops.Single(a => a.Name == "Digma"), GoodArtUrl = "/Content/Images/10.3.jpg" },                              
               new Goods { Title = "Optima 7.07 3G", products = products.Single(g => g.Name == "Планшет"), Price = 3700, 
                    Laptop = laptops.Single(a => a.Name == "Digma"), GoodArtUrl = "/Content/Images/7.07.jpg" },               
               new Goods { Title = "Eve 8.1 3G", products = products.Single(g => g.Name == "Планшет"), Price = 9380, 
                    Laptop = laptops.Single(a => a.Name == "Digma"), GoodArtUrl = "/Content/Images/8.1.jpg" },                
               new Goods { Title = "Optima 10.1 3G", products = products.Single(g => g.Name == "Планшет"), Price = 5790, 
                    Laptop = laptops.Single(a => a.Name == "Digma"), GoodArtUrl = "/Content/Images/10.1.jpg" },               
               new Goods { Title = "M728G", products = products.Single(g => g.Name == "Планшет"), Price = 4340, 
                    Laptop = laptops.Single(a => a.Name == "Supra"), GoodArtUrl = "/Content/Images/m728g.jpg" },                
               new Goods { Title = "M143g", products = products.Single(g => g.Name == "Планшет"), Price = 8100, 
                    Laptop = laptops.Single(a => a.Name == "Supra"), GoodArtUrl = "/Content/Images/m143g.jpg" },



               new Goods { Title = "iPhone 6 16Gb", products = products.Single(g => g.Name == "Смартфон"), Price = 37990, 
                    Laptop = laptops.Single(a => a.Name == "Apple"), GoodArtUrl = "/Content/Images/iphone6.jpg" },               
               new Goods { Title = "Galaxy S5", products = products.Single(g => g.Name == "Смартфон"), Price = 23490, 
                    Laptop = laptops.Single(a => a.Name == "Samsung"), GoodArtUrl = "/Content/Images/galaxys5.jpg" },               
               new Goods { Title = "Xperia Z3 Compact", products = products.Single(g => g.Name == "Смартфон"), Price = 22800, 
                    Laptop = laptops.Single(a => a.Name == "Sony"), GoodArtUrl = "/Content/Images/z3c.jpg" },               
               new Goods { Title = "Xperia Z3", products = products.Single(g => g.Name == "Смартфон"), Price = 27600, 
                    Laptop = laptops.Single(a => a.Name == "Sony"), GoodArtUrl = "/Content/Images/z3.jpg" },               
               new Goods { Title = "Zenfone", products = products.Single(g => g.Name == "Смартфон"), Price = 10200, 
                    Laptop = laptops.Single(a => a.Name == "Asus"), GoodArtUrl = "/Content/Images/zen5.jpg" },               
               new Goods { Title = "Vibe X2", products = products.Single(g => g.Name == "Смартфон"), Price = 14000, 
                    Laptop = laptops.Single(a => a.Name == "Lenovo"), GoodArtUrl = "/Content/Images/vibex2.jpg" },               
               new Goods { Title = "Lumia 830", products = products.Single(g => g.Name == "Смартфон"), Price = 13700, 
                    Laptop = laptops.Single(a => a.Name == "Nokia"), GoodArtUrl = "/Content/Images/830.jpg" },                
               new Goods { Title = "S850", products = products.Single(g => g.Name == "Смартфон"), Price = 9280, 
                    Laptop = laptops.Single(a => a.Name == "Lenovo"), GoodArtUrl = "/Content/Images/s850.jpg" },               
               new Goods { Title = "G3 s", products = products.Single(g => g.Name == "Смартфон"), Price = 11360, 
                    Laptop = laptops.Single(a => a.Name == "LG"), GoodArtUrl = "/Content/Images/g3s.jpg" },
               new Goods { Title = "A606", products = products.Single(g => g.Name == "Смартфон"), Price = 5890, 
                    Laptop = laptops.Single(a => a.Name == "Lenovo"), GoodArtUrl = "/Content/Images/a606.jpg" },                  
               new Goods { Title = "Lumia 535", products = products.Single(g => g.Name == "Смартфон"), Price = 6590, 
                    Laptop = laptops.Single(a => a.Name == "Microsoft"), GoodArtUrl = "/Content/Images/535.jpg" },               
               new Goods { Title = "Lumia 532", products = products.Single(g => g.Name == "Смартфон"), Price = 5250, 
                    Laptop = laptops.Single(a => a.Name == "Microsoft"), GoodArtUrl = "/Content/Images/532.jpg" },               
               new Goods { Title = "Lumia 640", products = products.Single(g => g.Name == "Смартфон"), Price = 12990, 
                    Laptop = laptops.Single(a => a.Name == "Microsoft"), GoodArtUrl = "/Content/Images/640.jpg" },               
               new Goods { Title = "Lumia 435", products = products.Single(g => g.Name == "Смартфон"), Price = 4400, 
                    Laptop = laptops.Single(a => a.Name == "Microsoft"), GoodArtUrl = "/Content/Images/435.jpg" },               
               new Goods { Title = "Lumia 430", products = products.Single(g => g.Name == "Смартфон"), Price = 4900, 
                    Laptop = laptops.Single(a => a.Name == "Microsoft"), GoodArtUrl = "/Content/Images/430.jpg" },                              
               new Goods { Title = "IQ4512 EVO Chic 4 Quad", products = products.Single(g => g.Name == "Смартфон"), Price = 7150, 
                    Laptop = laptops.Single(a => a.Name == "Fly"), GoodArtUrl = "/Content/Images/iq4512.jpg" },               
               new Goods { Title = "IQ4413 EVO Chic 3 Quad", products = products.Single(g => g.Name == "Смартфон"), Price = 5490, 
                    Laptop = laptops.Single(a => a.Name == "Fly"), GoodArtUrl = "/Content/Images/iq4413.jpg" },                
               new Goods { Title = "IQ4516 Tornado Slim Octa", products = products.Single(g => g.Name == "Смартфон"), Price = 13950, 
                    Laptop = laptops.Single(a => a.Name == "Fly"), GoodArtUrl = "/Content/Images/iq4516.jpg" },               
               new Goods { Title = "IQ4490i ERA Nano 10", products = products.Single(g => g.Name == "Смартфон"), Price = 3190, 
                    Laptop = laptops.Single(a => a.Name == "Fly"), GoodArtUrl = "/Content/Images/iq4490.jpg" },                
               new Goods { Title = "IQ4503 ERA Life 6 Quad", products = products.Single(g => g.Name == "Смартфон"), Price = 5190, 
                    Laptop = laptops.Single(a => a.Name == "Fly"), GoodArtUrl = "/Content/Images/iq4503.jpg" },                                 
               new Goods { Title = "Idol 2 6037Y", products = products.Single(g => g.Name == "Смартфон"), Price = 6990, 
                    Laptop = laptops.Single(a => a.Name == "Alcatel"), GoodArtUrl = "/Content/Images/6037y.jpg"},               
               new Goods { Title = "Pop S7 7045Y", products = products.Single(g => g.Name == "Смартфон"), Price = 6790, 
                    Laptop = laptops.Single(a => a.Name == "Alcatel"), GoodArtUrl = "/Content/Images/7045y.jpg"},               
               new Goods { Title = "Pop S9 7050Y", products = products.Single(g => g.Name == "Смартфон"), Price = 8100, 
                    Laptop = laptops.Single(a => a.Name == "Alcatel"), GoodArtUrl = "/Content/Images/7050y.jpg" },              
               new Goods { Title = "Idol 2 Mini 6016X", products = products.Single(g => g.Name == "Смартфон"), Price = 6390, 
                    Laptop = laptops.Single(a => a.Name == "Alcatel"), GoodArtUrl = "/Content/Images/6016x.jpg" },               
               new Goods { Title = "POP C9 7047D", products = products.Single(g => g.Name == "Смартфон"), Price = 6500, 
                    Laptop = laptops.Single(a => a.Name == "Alcatel"), GoodArtUrl = "/Content/Images/7047d.jpg" },               
               new Goods { Title = "Xenium W6610", products = products.Single(g => g.Name == "Смартфон"), Price = 10200, 
                    Laptop = laptops.Single(a => a.Name == "Philips"), GoodArtUrl = "/Content/Images/w6610.jpg" },               
               new Goods { Title = "Xenium V387", products = products.Single(g => g.Name == "Смартфон"), Price = 11100, 
                    Laptop = laptops.Single(a => a.Name == "Philips"), GoodArtUrl = "/Content/Images/v387.jpg" },               
               new Goods { Title = "Xenium I908", products = products.Single(g => g.Name == "Смартфон"), Price = 12990, 
                    Laptop = laptops.Single(a => a.Name == "Philips"), GoodArtUrl = "/Content/Images/i908.jpg" },              
               new Goods { Title = "IQ4490i ERA Nano 10", products = products.Single(g => g.Name == "Смартфон"), Price = 4390, 
                    Laptop = laptops.Single(a => a.Name == "Philips"), GoodArtUrl = "/Content/Images/s308.jpg" },                
               new Goods { Title = "IQ4503 ERA Life 6 Quad", products = products.Single(g => g.Name == "Смартфон"), Price = 12450, 
                    Laptop = laptops.Single(a => a.Name == "Philips"), GoodArtUrl = "/Content/Images/i928.jpg" },
 

               new Goods { Title = "Mini 515", products = products.Single(g => g.Name == "Эл.книга"), Price = 4290, 
                    Laptop = laptops.Single(a => a.Name == "PocketBook"), GoodArtUrl = "/Content/Images/515.jpg" },               
               new Goods { Title = "Basic 2 614", products = products.Single(g => g.Name == "Эл.книга"), Price = 5900, 
                    Laptop = laptops.Single(a => a.Name == "PocketBook"), GoodArtUrl = "/Content/Images/614.jpg" },               
               new Goods { Title = "Touch 2 626", products = products.Single(g => g.Name == "Эл.книга"), Price = 7480, 
                    Laptop = laptops.Single(a => a.Name == "PocketBook"), GoodArtUrl = "/Content/Images/626.jpg" },               
               new Goods { Title = "Kindle 6", products = products.Single(g => g.Name == "Эл.книга"), Price = 4290, 
                    Laptop = laptops.Single(a => a.Name == "Amazon"), GoodArtUrl = "/Content/Images/k6.jpg" },               
               new Goods { Title = "Kindle Paperwhite", products = products.Single(g => g.Name == "Эл.книга"), Price = 7250, 
                    Laptop = laptops.Single(a => a.Name == "Amazon"), GoodArtUrl = "/Content/Images/pape.jpg" },               
               new Goods { Title = "MagicBook Z6", products = products.Single(g => g.Name == "Эл.книга"), Price = 3290, 
                    Laptop = laptops.Single(a => a.Name == "Gmini"), GoodArtUrl = "/Content/Images/z6.jpg" },               
               new Goods { Title = "BOOX i63ML Newton", products = products.Single(g => g.Name == "Эл.книга"), Price = 9850, 
                    Laptop = laptops.Single(a => a.Name == "Onyx"), GoodArtUrl = "/Content/Images/i63ml.jpg" },                
               new Goods { Title = "BOOX T76ML Cleopatra", products = products.Single(g => g.Name == "Эл.книга"), Price = 12750, 
                    Laptop = laptops.Single(a => a.Name == "Onyx"), GoodArtUrl = "/Content/Images/t76ml.jpg" },               
               new Goods { Title = "BOOX C67SM Bering 2", products = products.Single(g => g.Name == "Эл.книга"), Price = 5090, 
                    Laptop = laptops.Single(a => a.Name == "Onyx"), GoodArtUrl = "/Content/Images/c67sm.jpg" },
               new Goods { Title = "MagicBook T6LHD", products = products.Single(g => g.Name == "Эл.книга"), Price = 4850, 
                    Laptop = laptops.Single(a => a.Name == "Gmini"), GoodArtUrl = "/Content/Images/t6lhd.jpg" },               
               new Goods { Title = "Nook Simple Touch", products = products.Single(g => g.Name == "Эл.книга"), Price = 5090, 
                    Laptop = laptops.Single(a => a.Name == "Barnes & Noble"), GoodArtUrl = "/Content/Images/nst.jpg" },
               new Goods { Title = "Nook Simple Touch with GlowLight", products = products.Single(g => g.Name == "Эл.книга"), Price = 8400, 
                    Laptop = laptops.Single(a => a.Name == "Barnes & Noble"), GoodArtUrl = "/Content/Images/glowlight.jpg" },                
               new Goods { Title = "Nook GlowLight", products = products.Single(g => g.Name == "Эл.книга"), Price = 8890, 
                    Laptop = laptops.Single(a => a.Name == "Barnes & Noble"), GoodArtUrl = "/Content/Images/ngl.jpg" },               
               new Goods { Title = "Nook 3G+Wi-Fi", products = products.Single(g => g.Name == "Эл.книга"), Price = 6300, 
                    Laptop = laptops.Single(a => a.Name == "Barnes & Noble"), GoodArtUrl = "/Content/Images/n3g.jpg" },                
               new Goods { Title = "Nook Color", products = products.Single(g => g.Name == "Эл.книга"), Price = 10000, 
                    Laptop = laptops.Single(a => a.Name == "Barnes & Noble"), GoodArtUrl = "/Content/Images/ncolor.jpg" },                 
				new Goods { Title = "BOOK E6005", products = products.Single(g => g.Name == "Эл.книга"), Price = 1350, 
                    Laptop = laptops.Single(a => a.Name == "Wexler"), GoodArtUrl = "/Content/Images/7205.jpg" },               
               new Goods { Title = "BOOK T7206", products = products.Single(g => g.Name == "Эл.книга"), Price = 1690, 
                    Laptop = laptops.Single(a => a.Name == "Wexler"), GoodArtUrl = "/Content/Images/7206.jpg" },                
               new Goods { Title = "BOOK E6005", products = products.Single(g => g.Name == "Эл.книга"), Price = 5500, 
                    Laptop = laptops.Single(a => a.Name == "Wexler"), GoodArtUrl = "/Content/Images/6005.jpg" },
               new Goods { Title = "BOOK T5002", products = products.Single(g => g.Name == "Эл.книга"), Price = 1990, 
                    Laptop = laptops.Single(a => a.Name == "Wexler"), GoodArtUrl = "/Content/Images/5002.jpg" },
               new Goods { Title = "BOOK E6001", products = products.Single(g => g.Name == "Эл.книга"), Price = 4290, 
                    Laptop = laptops.Single(a => a.Name == "Wexler"), GoodArtUrl = "/Content/Images/6001.jpg" }

                
            
            
            }.ForEach(a => context.Goods.Add(a));  
        }
    }
}